asset_manager/asset_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("employee.urls"))
]

asset_manager/employee/urls.py
from django.urls import path
from . import views

app_name = "employee"
urlpatterns = [
    path("", views.employee_login, name='employee_login'),
    path("employee_details/", views.employee_details, name='employee_details'),
    path("add_employee/", views.add_employee, name='add_employee'),
    path("add_stock/", views.add_stock, name='add_stock'),
    path("stock_details/", views.stock_details, name='stock_details'),
    path("logout_user/", views.logout_user, name='logout_user'),
    path("employee_stock_map/", views.employee_stock_map, name='employee_stock_map'),
    ]

asset_manager/employee/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    phone_no = models.CharField(max_length=13)
    address = models.TextField()
    is_employee_master = models.BooleanField(default=False)
    is_asset_master = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Stock(models.Model):
    name = models.CharField(max_length=150)
    no_of_items = models.IntegerField()
    operating_system = models.CharField(max_length=50)
    specifications = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class EmployeeStockKeyMap(models.Model):
    status_choices = [('Pending', 'Pending'), ('Not Issued', 'Not Issued'), ('With User', 'With User')]
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    asset = models.ForeignKey(Stock, on_delete=models.CASCADE)
    issued_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=status_choices, max_length=10)

    def __str__(self):
        return self.employee.user.username

asset_manager/employee/forms.py
from django.forms import ModelForm
from .models import Employee, EmployeeStockKeyMap, Stock, User


class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        exclude = ['is_employee_master','is_asset_master','user']


class StockForm(ModelForm):
    class Meta:
        model = Stock
        fields = "__all__"


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'username','email']


class EmployeeStockForm(ModelForm):
    class Meta:
        model = EmployeeStockKeyMap
        fields = ['employee', 'asset']

    def __init__(self, *args, **kwargs):
        super(EmployeeStockForm, self).__init__(*args, **kwargs)
        self.fields["asset"].queryset = Stock.objects.filter(no_of_items__gt=0)

asset_manager/employee/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .forms import EmployeeForm, UserForm, EmployeeStockForm, StockForm
from django.contrib.auth.models import User
from .models import Employee, Stock


def employee_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if user.employee.is_employee_master:
                return HttpResponseRedirect(reverse('employee:employee_details'))
            elif user.employee.is_asset_master:
                return HttpResponseRedirect(reverse('employee:stock_details'))
            else:
                return HttpResponseRedirect(reverse('employee:employee_details'))
        else:
            return render(request, "employee/login.html")
    else:
        if request.user.is_authenticated:
            employee = Employee.objects.all()
            return render(request, "employee/employee_details.html", {"employee": employee})
        return render(request, "employee/login.html")


@login_required(login_url="/")
def add_employee(request):
    if not request.user.employee.is_employee_master:
        return HttpResponseRedirect(reverse('employee:employee_details'))
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        user = UserForm(request.POST)
        if form.is_valid() and user.is_valid():
            first_name = request.POST['first_name']
            username = request.POST['username']
            email = request.POST['email']
            user = User.objects.create_user(first_name, username, email)
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect(reverse('employee:employee_details'))
        else:
            return render(request, 'employee/add_employee.html')

    else:
        form = EmployeeForm()
        user = UserForm()
        return render(request, 'employee/add_employee.html', {'form': form, 'user': user})


@login_required(login_url="/")
def employee_details(request):
    employee = Employee.objects.all()
    return render(request, "employee/employee_details.html", {"employee": employee})


@login_required(login_url="/")
def add_stock(request):
    if not request.user.employee.is_asset_master:
        return HttpResponseRedirect(reverse('employee:stock_details'))
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('employee:stock_details'))
    else:
        form = StockForm()
        return render(request,'employee/stock_entry.html', {'form': form})


@login_required(login_url="/")
def stock_details(request):
    stock = Stock.objects.all()
    return render(request, 'employee/stock_details.html', {'stock': stock})


def logout_user(request):
    logout(request)
    return render(request, 'employee/login.html')


@login_required(login_url="/")
def employee_stock_map(request):
    if request.method == "POST":
        form = EmployeeStockForm(request.POST)
        if form.is_valid():
            form.save()
            stock_obj = Stock.objects.get(id=request.POST["asset"])
            stock_obj.no_of_items = stock_obj.no_of_items - 1
            stock_obj.save(update_fields=["no_of_items"])
            return HttpResponseRedirect(reverse('employee:stock_details'), {'form': form})
        else:
            return render(request, "employee/employee_stock.html")
    else:
        form = EmployeeStockForm()
        return render(request, "employee/employee_stock.html",  {'form': form})

asset_manager/employee/templates/employee/add_employee.html
{% extends './base.html' %}

<!-- Page Content -->
{% block content %}
<div class="row" style="margin-top: 40px;">
    <a href="{% url 'employee:logout_user' %}" class="col-12 col-sm" role="button" aria-pressed="true" style="text-align: end;">Log Out</a>
    <a href="{% url 'employee:employee_details' %}" class="col-1 col-sm" role="button" aria-pressed="true">Employee Details</a>
</div>

<div class="wrapper fadeInDown" style="margin-top: 40px;">
    <div id="formContent">
        <!-- Login Form -->
        <div class="row">
            <form action="{% url 'employee:add_employee' %}" method="post">
                {% csrf_token %}
                <div class="col-md-4">
                    <center><h3>Employee Registration</h3></center>
                    <div class=".col-md-6 .offset-md-3">
                        <label for="first_name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" aria-describedby="emailHelp">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class=".col-md-6 .offset-md-3">
                        <label for="username" class="form-label">User Name</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class=".col-md-6 .offset-md-3">
                        <label class="form-label" for="phone_no">Mobile Number</label>
                        <input type="number" class="form-control" id="phone_no" name="phone_no">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class=".col-md-6 .offset-md-3">
                        <label class="form-label" for="address">Address</label>
                        <input type="text" class="form-control" id="address" name="address">
                    </div>
                </div>
                <div class="col-md-4">
                    <br>
                    <center>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </center>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

asset_manager/employee/templates/employee/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
            integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap5.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block css%}
    {% endblock %}
    {% block js %}
    {% endblock %}
    <title>Home Page</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

asset_manager/employee/templates/employee/employee_details.html
{% extends './base.html' %}

<!--CSS stylesheets-->
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css">
<style type="text/css">
        tfoot input {
            width: 100%;
            padding: 3px;
            box-sizing: border-box;
        }
</style>
{% endblock %}

<!-- JavaScript -->
{% block js %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript">
        $(document).ready(function() {
            $('#employee').DataTable({
                "pageLength": 5
            });
        } );
</script>
{% endblock %}

<!-- Page Content -->
{% block content %}
<div class="row">
    <a href="{% url 'employee:add_employee' %}" class="col-1 col-sm" role="button" aria-pressed="true">Add Employee</a>
    <a href="{% url 'employee:stock_details' %}" class="col-1 col-sm" role="button" aria-pressed="true">Stock Details</a>
    <a href="{% url 'employee:logout_user' %}" class="col-8 col-sm" role="button" aria-pressed="true" style="text-align: end;">Log Out</a>
</div>
<div class="row" style="margin-top: 40px;">
    <br>
    <table id="employee" class="table table-striped table-bordered" style="width:100%; margin-top: 40px;">
        <thead>
        <tr>
            <th>User Name</th>
            <th>Mobile Number</th>
            <th>Email</th>
            <th>Address</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employee %}
        <tr>
            <td>{{employee.user.username}}</td>
            <td>{{employee.phone_no}}</td>
            <td>{{employee.user.email}}</td>
            <td>{{employee.address}}</td>
            <br>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

asset_manager/employee/templates/employee/employee_stock.html
<!-- Page Content -->
{% extends './base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    <a href="{% url 'employee:employee_details' %}" class="col-1 col-sm" role="button" aria-pressed="true">Employee Details</a>
    <a href="{% url 'employee:stock_details' %}" class="col-1 col-sm" role="button" aria-pressed="true">Stock Details</a>
    <a href="{% url 'employee:logout_user' %}" class="col-12 col-sm" role="button" aria-pressed="true" style="text-align: end;">Log Out</a>
<div class="wrapper fadeInDown" style="margin-top: 40px;">
    <div id="formContent">
        <!-- Login Form -->
        <div class="row">
            <form class="well contact-form" action="{% url 'employee:employee_stock_map' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

asset_manager/employee/templates/employee/login.html
{% extends './base.html' %}

<!--CSS stylesheets-->
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css">
<style type="text/css">
        tfoot input {
            width: 100%;
            padding: 3px;
            box-sizing: border-box;
        }
</style>
{% endblock %}

<!-- JavaScript -->
{% block js %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript">
        $(document).ready(function() {
            $('#employee').DataTable({
                "pageLength": 5
            });
        } );
</script>
{% endblock %}

<!-- Page Content -->
{% block content %}
<div class="wrapper fadeInDown" style="margin-top: 40px;">
    <div id="formContent">
        <!-- Login Form -->
        <div class="row">
            <form action="{% url 'employee:employee_login' %}" method="post">
                {% csrf_token %}
                <div class="col-md-4">
                <center><h3>Employee Login</h3></center>
                    <div class=".col-md-6 .offset-md-3">
                        <label for="username" class="form-label">User Name</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                </div>
                <div class="col-md-4">
                    <center>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </center>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

asset_manager/employee/templates/employee/stock_details.html
{% extends './base.html' %}

<!-- Page Content -->
{% block content %}
<div class="row">
    <a href="{% url 'employee:add_stock' %}" class="col-1 col-sm" role="button" aria-pressed="true">Add Stock</a>
    <a href="{% url 'employee:employee_details' %}" class="col-1 col-sm" role="button" aria-pressed="true">Employee Details</a>
    <a href="{% url 'employee:employee_stock_map' %}" class="col-1 col-sm" role="button" aria-pressed="true">Assets Assign</a>
    <a href="{% url 'employee:logout_user' %}" class="col-12 col-sm" role="button" aria-pressed="true" style="text-align: end;">Log Out</a>
</div>
<div class="row" style="margin-top: 40px;">
    <br>
    <table id="employee" class="table table-striped table-bordered" style="width:100%; margin-top: 40px;">
        <thead>
        <tr>
            <th>Name</th>
            <th>Number Of Items</th>
            <th>Operating System</th>
            <th>Specifications</th>
        </tr>
        </thead>
        <tbody>
        {% for stock in stock %}
        <tr>
            <td>{{stock.name}}</td>
            <td>{{stock.no_of_items}}</td>
            <td>{{stock.operating_system}}</td>
            <td>{{stock.specifications}}</td>
            <br>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

asset_manager/employee/templates/employee/stock_entry.html
{% extends './base.html' %}

<!-- Page Content -->
{% block content %}
<div class="row">
    <a href="{% url 'employee:employee_details' %}" class="col-1 col-sm" role="button" aria-pressed="true">Employee Details</a>
    <a href="{% url 'employee:logout_user' %}" class="col-12 col-sm" role="button" aria-pressed="true" style="text-align: end;">Log Out</a>
</div>
<div class="wrapper fadeInDown" style="margin-top: 40px;">
    <div id="formContent">
        <!-- Login Form -->
        <div class="row">
            <form action="{% url 'employee:add_stock' %}" method="post">
                {% csrf_token %}
                <div class="col-md-4">
                    <center><h3>Stock Entry</h3></center>
                    <div class=".col-md-6 .offset-md-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class=".col-md-6 .offset-md-3">
                        <label for="no_of_items" class="form-label">No Of Items</label>
                        <input type="number" class="no_of_items" id="no_of_items" name="no_of_items">
                    </div>
                    <div class="mb-3">
                        <label for="operating_system" class="form-label">OS</label>
                        <input type="text" class="operating_system" id="operating_system" name="operating_system">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class=".col-md-6 .offset-md-3">
                        <label class="form-label" for="specifications">Specifications</label>
                        <input type="specifications" class="form-control" id="specifications" name="specifications">
                    </div>
                </div>
                <div class="col-md-4">
                    <center>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </center>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}